name: Build/Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build and Publish
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npm run build:exe
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            npm run build:mac:universal
          elif [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            npm run build:linux
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: ${{ secrets.WINDOWS_CERTIFICATE }}
          CSC_KEY_PASSWORD: ${{ secrets.WINDOWS_CERTIFICATE_PASSWORD }}
